// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTbMyphHPZW-tLx9vaS4SmRHl8ujGyw4E',
    appId: '1:158217576757:web:92866d942f9329d6e9ec7c',
    messagingSenderId: '158217576757',
    projectId: 'amthalshaabeya',
    authDomain: 'amthalshaabeya.firebaseapp.com',
    storageBucket: 'amthalshaabeya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf4QfzPwMPtFBDzcREViAANnHcxfwaop8',
    appId: '1:158217576757:android:d82c777d5350e18ae9ec7c',
    messagingSenderId: '158217576757',
    projectId: 'amthalshaabeya',
    storageBucket: 'amthalshaabeya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYt59K2vm3LnVVah_uM_y8nK2PWU6SJqo',
    appId: '1:158217576757:ios:228253948bd08145e9ec7c',
    messagingSenderId: '158217576757',
    projectId: 'amthalshaabeya',
    storageBucket: 'amthalshaabeya.appspot.com',
    iosBundleId: 'com.example.amthaSha3beyaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYt59K2vm3LnVVah_uM_y8nK2PWU6SJqo',
    appId: '1:158217576757:ios:29e5e98f77bc9b5ae9ec7c',
    messagingSenderId: '158217576757',
    projectId: 'amthalshaabeya',
    storageBucket: 'amthalshaabeya.appspot.com',
    iosBundleId: 'com.example.amthaSha3beyaAdmin.RunnerTests',
  );
}
